// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4_PnxG1jsfpsd_R7ETrUxagMmJquQRas',
    appId: '1:442439926476:web:2563b331d806f543173869',
    messagingSenderId: '442439926476',
    projectId: 'cafe-z',
    authDomain: 'cafe-z.firebaseapp.com',
    databaseURL: 'https://cafe-z-default-rtdb.firebaseio.com',
    storageBucket: 'cafe-z.appspot.com',
    measurementId: 'G-W3N3PMMBFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2LBdYsYE9Lx8orsCqYaS-QKxlNKFyRKU',
    appId: '1:442439926476:android:45a65b3f6de1f525173869',
    messagingSenderId: '442439926476',
    projectId: 'cafe-z',
    databaseURL: 'https://cafe-z-default-rtdb.firebaseio.com',
    storageBucket: 'cafe-z.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJNg_5B26Q2sxz8gVhINfSuDPpadEkJUk',
    appId: '1:442439926476:ios:238b7f87396e9c65173869',
    messagingSenderId: '442439926476',
    projectId: 'cafe-z',
    databaseURL: 'https://cafe-z-default-rtdb.firebaseio.com',
    storageBucket: 'cafe-z.appspot.com',
    iosBundleId: 'com.example.cafez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJNg_5B26Q2sxz8gVhINfSuDPpadEkJUk',
    appId: '1:442439926476:ios:2d95e4d22ac3765a173869',
    messagingSenderId: '442439926476',
    projectId: 'cafe-z',
    databaseURL: 'https://cafe-z-default-rtdb.firebaseio.com',
    storageBucket: 'cafe-z.appspot.com',
    iosBundleId: 'com.example.cafez.RunnerTests',
  );
}
